
@baseUrl = https://us-central1-cooknotes-backend.cloudfunctions.net/api/


### Get the list of users
GET {{baseUrl}}/users

###  Getting a user for a given id
GET {{baseUrl}}/users/SzjLGyjRf5UQMmtDTbnO


###  Add a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
               "username": "umair",
                "displayName": "Umair Hamzah",
                "profilePic": "assets/tony.jpg",
                "usertype": "U",
                "age": "21",
                "email": "umair.bzk@gmail.com",
                "password": "Abc123",
                "recipe": [

                    {
                        "foodName": "Asam Pedas",
                        "image": "assets/asampedas.jpg",
                        "prepHours": 0,
                        "prepMins": 30,
                        "cookHours": 1,
                        "cookMins": 30,
                        "numPerson": 5,
                        "ingredients": "ikan\nasam\nsantan\nbawang",
                        "instruction": "masak sampai sedap"
                    },

                    {
                        "foodName": "Chicken Lasagna",
                        "image": "assets/chickenlasagna.jpg",
                        "prepHours": 0,
                        "prepMins": 40,
                        "cookHours": 2,
                        "cookMins": 0,
                        "numPerson": 1,
                        "ingredients": "chicken\nlasagna\ncheese",
                        "instruction": "masak sampai sedap"
                    },

                    {
                        "foodName": "Ayam Goreng Crispy",
                        "image": "assets/ayamgoreng.jpg",
                        "prepHours": 0,
                        "prepMins": 15,
                        "cookHours": 0,
                        "cookMins": 30,
                        "numPerson": 4,
                        "ingredients": "ayam\nbawang\ntepung",
                        "instruction": "masak sampai sedap"
                    },
                    {
                        "foodName": "Ikan Siakap Tiga Rasa",
                        "image": "assets/siakap.jpg",
                        "prepHours": 0,
                        "prepMins": 40,
                        "cookHours": 2,
                        "cookMins": 0,
                        "numPerson": 1,
                        "ingredients": "ikan\nsos\ntepung jagung",
                        "instruction": "masak sampai sedap ye!"
                    }
                ],
                "article": [{
                        "title": "",
                        "image": "",
                        "author": "",
                        "content": "",
                    },
                ]
            
}

### Update a user 
PATCH {{baseUrl}}/users/SzjLGyjRf5UQMmtDTbnO

Content-Type: application/json

{
        "username": "umairun",
                "displayName": "Umairun Hamzah",
                "profilePic": "assets/tony.jpg",
                "usertype": "U",
                "age": "21",
                "email": "umairun.bzk@gmail.com",
                "password": "Abc123",
                "recipe": [

                    {
                        "foodName": "Asam Pedas",
                        "image": "assets/asampedas.jpg",
                        "prepHours": 0,
                        "prepMins": 30,
                        "cookHours": 1,
                        "cookMins": 30,
                        "numPerson": 5,
                        "ingredients": "ikan\nasam\nsantan\nbawang",
                        "instruction": "masak sampai sedap"
                    },

                    {
                        "foodName": "Chicken Lasagna",
                        "image": "assets/chickenlasagna.jpg",
                        "prepHours": 0,
                        "prepMins": 40,
                        "cookHours": 2,
                        "cookMins": 0,
                        "numPerson": 1,
                        "ingredients": "chicken\nlasagna\ncheese",
                        "instruction": "masak sampai sedap"
                    },

                    {
                        "foodName": "Ayam Goreng Crispy",
                        "image": "assets/ayamgoreng.jpg",
                        "prepHours": 0,
                        "prepMins": 15,
                        "cookHours": 0,
                        "cookMins": 30,
                        "numPerson": 4,
                        "ingredients": "ayam\nbawang\ntepung",
                        "instruction": "masak sampai sedap"
                    },
                    {
                        "foodName": "Ikan Siakap Tiga Rasa",
                        "image": "assets/siakap.jpg",
                        "prepHours": 0,
                        "prepMins": 40,
                        "cookHours": 2,
                        "cookMins": 0,
                        "numPerson": 1,
                        "ingredients": "ikan\nsos\ntepung jagung",
                        "instruction": "masak sampai sedap ye!"
                    }
                ],
                "article": [{
                        "title": "",
                        "image": "",
                        "author": "",
                        "content": "",
                    },
                ]
}

### Delete a user
DELETE {{baseUrl}}/users/SzjLGyjRf5UQMmtDTbnO


